services:
  app:
    build: .
    command: yarn start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
  db:
    container_name: 'database-node'
    image: mysql
    restart: always
    ports: 
      - '3308:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: