services:
  app:
    build: . #Indica o diretorio do Dockerfile
    command: npm start
    restart: always # Se o container cair ele vai reiniciar
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app #. Oque sera copiado para : usr/app
      #- ./dist:/usr/app teste não funcionou
    links:
      - mongo
      - db
  db:
    container_name: 'database-node'
    image: mysql
    restart: always
    ports: 
      - '3308:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    volumes:
      - my-db:/var/lib/mysql
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27017
    
volumes:
  my-db: